const siteMetadata = {
  title: "Gestures",
  author: "Harmeet Singh",
  headerTitle: "Gestures",
  description: "Settle your friendly disputes on web3 with Gestures",
  language: "en-us",
  locale: "en-US",
  type: "website",
  url: process.env.NEXT_PUBLIC_BASE_URL,
  theme: "system",
  siteUrl: process.env.NEXT_PUBLIC_BASE_URL,
  siteLogo: "/icon.svg",
  socialBanner: "/logo.png",
  email: "waraichharman68@gmail.com",
  github: "https://github.com/Harman-singh-waraich",
  twitter: "https://twitter.com/TurbanCoder",
  linkedin: "https://www.linkedin.com/in/turban-coder/",
  robots: "index, follow",
  keywords: "rock paper scissor lizard spock game web3",
  sitename: "Gestures",
};
export default siteMetadata;
